### ISSUE TITLE
Consider breaking cookbooks into separate git projects 

### ISSUE THREAD

**Issue by poliva83** [melezhik/cookbooks#25]
If the cookbooks lived in own projects it would give you ability to do proper releases and tag commits. I attempted to try and mirror just the span cookbook but realized trying to figure out when older versions  of cpan were released is a pita.

**Comment by melezhik** [comment]
Agree, this is more convenient way. But now unfortunately I am not actively developing this stuff. Feel free to fork and reorganize the structure as you wish.
Also despite the fact all things now resides  in single git repository, every cookbook holds changes files to help you with version history , e.g. - https://github.com/melezhik/cookbooks/blob/master/cpan/changes.md

**Comment by poliva83** [comment]
ok thanks @melezhik, I did fork cpan cookbook internally as suggested. I may create new space in github for it in future.
