### ISSUE TITLE
License

### ISSUE THREAD

**Issue by iennae** [melezhik/cookbooks#33]
Hi!

The cpan cookbook looks to have a license "All rights reserved". Would you be willing to make this Apache-2.0 or any other OSI approved license https://opensource.org/licenses?

**Comment by melezhik** [comment]
Hi @iennae , yes I would. Could you send me a MR please? Or I can do that, but latter (:

**Comment by melezhik** [comment]
TODO:

need to bump versions and upload all into  supermarket ...

**Comment by iennae** [comment]
Thanks! This looks good on the supermarket now https://supermarket.chef.io/cookbooks/cpan
